name: AutoAssignment

on:
    pull_request:
        types: [opened, reopened, ready_for_review]

jobs:
    assignment:
        runs-on: ubuntu-latest
        steps:
            - name: Auto-assignment
              uses: kyoya0819/auto-assignment@v1.2.2
              with:
                  configuration-path: ".github/auto_assign_reviewer.yml"